// Code generated by ogen, DO NOT EDIT.
package oas

type GetAppsHistoryRes interface {
	getAppsHistoryRes()
}

type GetAppsPerPartitionPerQueueRes interface {
	getAppsPerPartitionPerQueueRes()
}

type GetContainersHistoryRes interface {
	getContainersHistoryRes()
}

type GetEventStatisticsRes interface {
	getEventStatisticsRes()
}

type GetNodeUtilizationsRes interface {
	getNodeUtilizationsRes()
}

type GetNodesPerPartitionRes interface {
	getNodesPerPartitionRes()
}

type GetPartitionsRes interface {
	getPartitionsRes()
}

type GetQueuesPerPartitionRes interface {
	getQueuesPerPartitionRes()
}
