// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAppsHistory implements getAppsHistory operation.
//
// Get applications history.
//
// GET /ws/v1/history/apps
func (UnimplementedHandler) GetAppsHistory(ctx context.Context) (r GetAppsHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAppsPerPartitionPerQueue implements getAppsPerPartitionPerQueue operation.
//
// Get applications for a queue in a partition.
//
// GET /ws/v1/partition/{partition_name}/queue/{queue_name}/applications
func (UnimplementedHandler) GetAppsPerPartitionPerQueue(ctx context.Context, params GetAppsPerPartitionPerQueueParams) (r GetAppsPerPartitionPerQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetContainersHistory implements getContainersHistory operation.
//
// Get containers history.
//
// GET /ws/v1/history/containers
func (UnimplementedHandler) GetContainersHistory(ctx context.Context) (r GetContainersHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventStatistics implements getEventStatistics operation.
//
// Get event statistics.
//
// GET /ws/v1/event-statistics
func (UnimplementedHandler) GetEventStatistics(ctx context.Context) (r GetEventStatisticsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNodeUtilizations implements getNodeUtilizations operation.
//
// Get node utilizations.
//
// GET /ws/v1/scheduler/node-utilizations
func (UnimplementedHandler) GetNodeUtilizations(ctx context.Context) (r GetNodeUtilizationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNodesPerPartition implements getNodesPerPartition operation.
//
// Get nodes for a partition.
//
// GET /ws/v1/partition/{partition_name}/nodes
func (UnimplementedHandler) GetNodesPerPartition(ctx context.Context, params GetNodesPerPartitionParams) (r GetNodesPerPartitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPartitions implements getPartitions operation.
//
// Get all partitions.
//
// GET /ws/v1/partitions
func (UnimplementedHandler) GetPartitions(ctx context.Context) (r GetPartitionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetQueuesPerPartition implements getQueuesPerPartition operation.
//
// Get queues for a partition.
//
// GET /ws/v1/partition/{partition_name}/queues
func (UnimplementedHandler) GetQueuesPerPartition(ctx context.Context, params GetQueuesPerPartitionParams) (r GetQueuesPerPartitionRes, _ error) {
	return r, ht.ErrNotImplemented
}
